
namespace SALES_AND_INVENTORY_SYSTEM_FOR_RI_RICE_MILL
{
    partial class frmReturnPayment
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmReturnPayment));
            Kimtoo.ValidationProvider.ValidationObject validationObject1 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject2 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject6 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject3 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject4 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject5 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Kimtoo.ValidationProvider.ValidationObject validationObject7 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Kimtoo.ValidationProvider.ValidationObject validationObject8 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject9 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Kimtoo.ValidationProvider.ValidationObject validationObject10 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Kimtoo.ValidationProvider.ValidationObject validationObject11 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Kimtoo.ValidationProvider.ValidationObject validationObject12 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject13 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Kimtoo.ValidationProvider.ValidationObject validationObject14 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Kimtoo.ValidationProvider.ValidationObject validationObject15 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Kimtoo.ValidationProvider.ValidationObject validationObject16 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject17 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject18 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject19 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Kimtoo.ValidationProvider.ValidationObject validationObject20 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject21 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject22 = new Kimtoo.ValidationProvider.ValidationObject();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnClose = new Bunifu.Framework.UI.BunifuTileButton();
            this.btnExit = new System.Windows.Forms.Button();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnConfirm = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtCash = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtAmount = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnAddCustomer = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtViewCustomer = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPWDOSCA = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtORNumber = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblPWDORSC = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblTransCount = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblTranstotal = new Bunifu.UI.WinForms.BunifuLabel();
            this.validationProvider1 = new Kimtoo.ValidationProvider.ValidationProvider();
            this.btnGenerateOR = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPanel1.SuspendLayout();
            this.bunifuPanel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Arial Rounded MT Bold", 12F);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.Black;
            validationObject1.CustomErrorMessage = "";
            validationObject1.Optional = false;
            validationObject1.PropertyName = "Text";
            validationObject1.Regex = null;
            validationObject1.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.bunifuLabel1, validationObject1);
            this.bunifuLabel1.Location = new System.Drawing.Point(37, 17);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(106, 18);
            this.bunifuLabel1.TabIndex = 48;
            this.bunifuLabel1.Text = "Total Amount";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopRight;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Impact", 20.25F);
            this.bunifuLabel4.ForeColor = System.Drawing.Color.Black;
            validationObject2.CustomErrorMessage = "";
            validationObject2.Optional = false;
            validationObject2.PropertyName = "Text";
            validationObject2.Regex = null;
            validationObject2.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.bunifuLabel4, validationObject2);
            this.bunifuLabel4.Location = new System.Drawing.Point(169, 101);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(243, 34);
            this.bunifuLabel4.TabIndex = 103;
            this.bunifuLabel4.Text = "SUMMARY OF PAYMENT";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.RoyalBlue;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 0;
            this.bunifuPanel1.BorderThickness = 0;
            this.bunifuPanel1.Controls.Add(this.btnClose);
            this.bunifuPanel1.Controls.Add(this.btnExit);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel3);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            validationObject6.CustomErrorMessage = "";
            validationObject6.Optional = false;
            validationObject6.PropertyName = "Text";
            validationObject6.Regex = null;
            validationObject6.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.bunifuPanel1, validationObject6);
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = false;
            this.bunifuPanel1.Size = new System.Drawing.Size(583, 38);
            this.bunifuPanel1.TabIndex = 105;
            // 
            // btnClose
            // 
            this.btnClose.BackColor = System.Drawing.Color.RoyalBlue;
            this.btnClose.color = System.Drawing.Color.RoyalBlue;
            this.btnClose.colorActive = System.Drawing.Color.IndianRed;
            this.btnClose.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnClose.Font = new System.Drawing.Font("Century Gothic", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClose.ForeColor = System.Drawing.Color.White;
            this.btnClose.Image = null;
            this.btnClose.ImagePosition = 21;
            this.btnClose.ImageZoom = 50;
            this.btnClose.LabelPosition = 43;
            this.btnClose.LabelText = "x";
            validationObject3.CustomErrorMessage = "";
            validationObject3.Optional = false;
            validationObject3.PropertyName = "Text";
            validationObject3.Regex = null;
            validationObject3.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.btnClose, validationObject3);
            this.btnClose.Location = new System.Drawing.Point(520, -9);
            this.btnClose.Margin = new System.Windows.Forms.Padding(8);
            this.btnClose.Name = "btnClose";
            this.btnClose.Size = new System.Drawing.Size(63, 56);
            this.btnClose.TabIndex = 102;
            this.btnClose.Click += new System.EventHandler(this.btnClose_Click);
            // 
            // btnExit
            // 
            this.btnExit.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(57)))), ((int)(((byte)(43)))));
            this.btnExit.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btnExit.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnExit.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(240)))), ((int)(((byte)(241)))));
            validationObject4.CustomErrorMessage = "";
            validationObject4.Optional = false;
            validationObject4.PropertyName = "Text";
            validationObject4.Regex = null;
            validationObject4.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.btnExit, validationObject4);
            this.btnExit.Location = new System.Drawing.Point(814, 0);
            this.btnExit.Name = "btnExit";
            this.btnExit.Size = new System.Drawing.Size(58, 38);
            this.btnExit.TabIndex = 101;
            this.btnExit.Text = "X";
            this.btnExit.UseVisualStyleBackColor = false;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Impact", 18F);
            this.bunifuLabel3.ForeColor = System.Drawing.Color.White;
            validationObject5.CustomErrorMessage = "";
            validationObject5.Optional = false;
            validationObject5.PropertyName = "Text";
            validationObject5.Regex = null;
            validationObject5.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.bunifuLabel3, validationObject5);
            this.bunifuLabel3.Location = new System.Drawing.Point(12, 6);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(86, 29);
            this.bunifuLabel3.TabIndex = 45;
            this.bunifuLabel3.Text = "PAYMENT";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnConfirm
            // 
            this.btnConfirm.AllowAnimations = true;
            this.btnConfirm.AllowMouseEffects = true;
            this.btnConfirm.AllowToggling = false;
            this.btnConfirm.AnimationSpeed = 200;
            this.btnConfirm.AutoGenerateColors = false;
            this.btnConfirm.AutoRoundBorders = false;
            this.btnConfirm.AutoSizeLeftIcon = true;
            this.btnConfirm.AutoSizeRightIcon = true;
            this.btnConfirm.BackColor = System.Drawing.Color.Transparent;
            this.btnConfirm.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnConfirm.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnConfirm.BackgroundImage")));
            this.btnConfirm.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnConfirm.ButtonText = "Confirm [Enter]";
            this.btnConfirm.ButtonTextMarginLeft = 0;
            this.btnConfirm.ColorContrastOnClick = 45;
            this.btnConfirm.ColorContrastOnHover = 45;
            this.btnConfirm.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnConfirm.CustomizableEdges = borderEdges1;
            this.btnConfirm.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnConfirm.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnConfirm.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnConfirm.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnConfirm.Enabled = false;
            this.btnConfirm.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnConfirm.Font = new System.Drawing.Font("Arial Rounded MT Bold", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnConfirm.ForeColor = System.Drawing.Color.White;
            this.btnConfirm.IconLeft = null;
            this.btnConfirm.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnConfirm.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnConfirm.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnConfirm.IconMarginLeft = 11;
            this.btnConfirm.IconPadding = 10;
            this.btnConfirm.IconRight = null;
            this.btnConfirm.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnConfirm.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnConfirm.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnConfirm.IconSize = 25;
            this.btnConfirm.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnConfirm.IdleBorderRadius = 0;
            this.btnConfirm.IdleBorderThickness = 0;
            this.btnConfirm.IdleFillColor = System.Drawing.Color.Empty;
            this.btnConfirm.IdleIconLeftImage = null;
            this.btnConfirm.IdleIconRightImage = null;
            this.btnConfirm.IndicateFocus = false;
            validationObject7.CustomErrorMessage = "";
            validationObject7.Optional = false;
            validationObject7.PropertyName = "Text";
            validationObject7.Regex = null;
            validationObject7.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.btnConfirm, validationObject7);
            this.btnConfirm.Location = new System.Drawing.Point(283, 463);
            this.btnConfirm.Name = "btnConfirm";
            this.btnConfirm.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnConfirm.OnDisabledState.BorderRadius = 1;
            this.btnConfirm.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnConfirm.OnDisabledState.BorderThickness = 1;
            this.btnConfirm.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnConfirm.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnConfirm.OnDisabledState.IconLeftImage = null;
            this.btnConfirm.OnDisabledState.IconRightImage = null;
            this.btnConfirm.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnConfirm.onHoverState.BorderRadius = 1;
            this.btnConfirm.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnConfirm.onHoverState.BorderThickness = 1;
            this.btnConfirm.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnConfirm.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnConfirm.onHoverState.IconLeftImage = null;
            this.btnConfirm.onHoverState.IconRightImage = null;
            this.btnConfirm.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnConfirm.OnIdleState.BorderRadius = 1;
            this.btnConfirm.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnConfirm.OnIdleState.BorderThickness = 1;
            this.btnConfirm.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnConfirm.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnConfirm.OnIdleState.IconLeftImage = null;
            this.btnConfirm.OnIdleState.IconRightImage = null;
            this.btnConfirm.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnConfirm.OnPressedState.BorderRadius = 1;
            this.btnConfirm.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnConfirm.OnPressedState.BorderThickness = 1;
            this.btnConfirm.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnConfirm.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnConfirm.OnPressedState.IconLeftImage = null;
            this.btnConfirm.OnPressedState.IconRightImage = null;
            this.btnConfirm.Size = new System.Drawing.Size(129, 39);
            this.btnConfirm.TabIndex = 3;
            this.btnConfirm.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnConfirm.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnConfirm.TextMarginLeft = 0;
            this.btnConfirm.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnConfirm.UseDefaultRadiusAndThickness = true;
            this.btnConfirm.Click += new System.EventHandler(this.btnConfirm_Click);
            // 
            // btnCancel
            // 
            this.btnCancel.AllowAnimations = true;
            this.btnCancel.AllowMouseEffects = true;
            this.btnCancel.AllowToggling = false;
            this.btnCancel.AnimationSpeed = 200;
            this.btnCancel.AutoGenerateColors = false;
            this.btnCancel.AutoRoundBorders = false;
            this.btnCancel.AutoSizeLeftIcon = true;
            this.btnCancel.AutoSizeRightIcon = true;
            this.btnCancel.BackColor = System.Drawing.Color.Transparent;
            this.btnCancel.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnCancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCancel.BackgroundImage")));
            this.btnCancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.ButtonText = "Cancel [Esc]";
            this.btnCancel.ButtonTextMarginLeft = 0;
            this.btnCancel.ColorContrastOnClick = 45;
            this.btnCancel.ColorContrastOnHover = 45;
            this.btnCancel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnCancel.CustomizableEdges = borderEdges2;
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCancel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnCancel.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnCancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCancel.Font = new System.Drawing.Font("Arial Rounded MT Bold", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.ForeColor = System.Drawing.Color.White;
            this.btnCancel.IconLeft = null;
            this.btnCancel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCancel.IconMarginLeft = 11;
            this.btnCancel.IconPadding = 10;
            this.btnCancel.IconRight = null;
            this.btnCancel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCancel.IconSize = 25;
            this.btnCancel.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnCancel.IdleBorderRadius = 0;
            this.btnCancel.IdleBorderThickness = 0;
            this.btnCancel.IdleFillColor = System.Drawing.Color.Empty;
            this.btnCancel.IdleIconLeftImage = null;
            this.btnCancel.IdleIconRightImage = null;
            this.btnCancel.IndicateFocus = false;
            validationObject8.CustomErrorMessage = "";
            validationObject8.Optional = false;
            validationObject8.PropertyName = "Text";
            validationObject8.Regex = null;
            validationObject8.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.btnCancel, validationObject8);
            this.btnCancel.Location = new System.Drawing.Point(156, 463);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.OnDisabledState.BorderRadius = 1;
            this.btnCancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnDisabledState.BorderThickness = 1;
            this.btnCancel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancel.OnDisabledState.IconLeftImage = null;
            this.btnCancel.OnDisabledState.IconRightImage = null;
            this.btnCancel.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnCancel.onHoverState.BorderRadius = 1;
            this.btnCancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.onHoverState.BorderThickness = 1;
            this.btnCancel.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnCancel.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.onHoverState.IconLeftImage = null;
            this.btnCancel.onHoverState.IconRightImage = null;
            this.btnCancel.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCancel.OnIdleState.BorderRadius = 1;
            this.btnCancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnIdleState.BorderThickness = 1;
            this.btnCancel.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnCancel.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.OnIdleState.IconLeftImage = null;
            this.btnCancel.OnIdleState.IconRightImage = null;
            this.btnCancel.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCancel.OnPressedState.BorderRadius = 1;
            this.btnCancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnPressedState.BorderThickness = 1;
            this.btnCancel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCancel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.OnPressedState.IconLeftImage = null;
            this.btnCancel.OnPressedState.IconRightImage = null;
            this.btnCancel.Size = new System.Drawing.Size(107, 39);
            this.btnCancel.TabIndex = 50;
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCancel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCancel.TextMarginLeft = 0;
            this.btnCancel.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCancel.UseDefaultRadiusAndThickness = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click_1);
            // 
            // txtCash
            // 
            this.txtCash.AcceptsReturn = false;
            this.txtCash.AcceptsTab = false;
            this.txtCash.AnimationSpeed = 200;
            this.txtCash.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCash.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCash.AutoSizeHeight = true;
            this.txtCash.BackColor = System.Drawing.Color.Transparent;
            this.txtCash.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCash.BackgroundImage")));
            this.txtCash.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCash.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCash.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCash.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCash.BorderRadius = 1;
            this.txtCash.BorderThickness = 1;
            this.txtCash.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCash.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCash.DefaultFont = new System.Drawing.Font("Arial", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCash.DefaultText = "";
            this.txtCash.FillColor = System.Drawing.Color.White;
            this.txtCash.HideSelection = true;
            this.txtCash.IconLeft = null;
            this.txtCash.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCash.IconPadding = 10;
            this.txtCash.IconRight = null;
            this.txtCash.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCash.Lines = new string[0];
            validationObject9.CustomErrorMessage = "Invalid Number";
            validationObject9.Optional = false;
            validationObject9.PropertyName = "Text";
            validationObject9.Regex = "^[0-9]*(\\.[0-9]{1,4})?$";
            validationObject9.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.Decimal;
            this.validationProvider1.SetLink(this.txtCash, validationObject9);
            this.txtCash.Location = new System.Drawing.Point(189, 386);
            this.txtCash.MaxLength = 13;
            this.txtCash.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCash.Modified = false;
            this.txtCash.Multiline = false;
            this.txtCash.Name = "txtCash";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCash.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCash.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCash.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCash.OnIdleState = stateProperties4;
            this.txtCash.Padding = new System.Windows.Forms.Padding(3);
            this.txtCash.PasswordChar = '\0';
            this.txtCash.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCash.PlaceholderText = "";
            this.txtCash.ReadOnly = false;
            this.txtCash.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCash.SelectedText = "";
            this.txtCash.SelectionLength = 0;
            this.txtCash.SelectionStart = 0;
            this.txtCash.ShortcutsEnabled = true;
            this.txtCash.Size = new System.Drawing.Size(176, 37);
            this.txtCash.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCash.TabIndex = 2;
            this.txtCash.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCash.TextMarginBottom = 0;
            this.txtCash.TextMarginLeft = 3;
            this.txtCash.TextMarginTop = 1;
            this.txtCash.TextPlaceholder = "";
            this.txtCash.UseSystemPasswordChar = false;
            this.txtCash.WordWrap = true;
            this.txtCash.TextChange += new System.EventHandler(this.txtCash_TextChanged);
            this.txtCash.TextChanged += new System.EventHandler(this.txtCash_TextChanged);
            this.txtCash.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txtCash_KeyPress);
            // 
            // txtAmount
            // 
            this.txtAmount.AcceptsReturn = false;
            this.txtAmount.AcceptsTab = false;
            this.txtAmount.AnimationSpeed = 200;
            this.txtAmount.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtAmount.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtAmount.AutoSizeHeight = true;
            this.txtAmount.BackColor = System.Drawing.Color.Transparent;
            this.txtAmount.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtAmount.BackgroundImage")));
            this.txtAmount.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtAmount.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtAmount.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtAmount.BorderColorIdle = System.Drawing.Color.White;
            this.txtAmount.BorderRadius = 1;
            this.txtAmount.BorderThickness = 1;
            this.txtAmount.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtAmount.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAmount.DefaultFont = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtAmount.DefaultText = "";
            this.txtAmount.Enabled = false;
            this.txtAmount.FillColor = System.Drawing.Color.Gainsboro;
            this.txtAmount.HideSelection = true;
            this.txtAmount.IconLeft = null;
            this.txtAmount.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAmount.IconPadding = 10;
            this.txtAmount.IconRight = null;
            this.txtAmount.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAmount.Lines = new string[0];
            validationObject10.CustomErrorMessage = "";
            validationObject10.Optional = false;
            validationObject10.PropertyName = "Text";
            validationObject10.Regex = null;
            validationObject10.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.txtAmount, validationObject10);
            this.txtAmount.Location = new System.Drawing.Point(154, 7);
            this.txtAmount.MaxLength = 10;
            this.txtAmount.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtAmount.Modified = false;
            this.txtAmount.Multiline = false;
            this.txtAmount.Name = "txtAmount";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAmount.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtAmount.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAmount.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.White;
            stateProperties8.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAmount.OnIdleState = stateProperties8;
            this.txtAmount.Padding = new System.Windows.Forms.Padding(3);
            this.txtAmount.PasswordChar = '\0';
            this.txtAmount.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtAmount.PlaceholderText = "";
            this.txtAmount.ReadOnly = false;
            this.txtAmount.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtAmount.SelectedText = "";
            this.txtAmount.SelectionLength = 0;
            this.txtAmount.SelectionStart = 0;
            this.txtAmount.ShortcutsEnabled = true;
            this.txtAmount.Size = new System.Drawing.Size(213, 35);
            this.txtAmount.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtAmount.TabIndex = 4;
            this.txtAmount.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtAmount.TextMarginBottom = 0;
            this.txtAmount.TextMarginLeft = 3;
            this.txtAmount.TextMarginTop = 1;
            this.txtAmount.TextPlaceholder = "";
            this.txtAmount.UseSystemPasswordChar = false;
            this.txtAmount.WordWrap = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14.25F);
            this.bunifuLabel5.ForeColor = System.Drawing.Color.Black;
            validationObject11.CustomErrorMessage = "";
            validationObject11.Optional = false;
            validationObject11.PropertyName = "Text";
            validationObject11.Regex = null;
            validationObject11.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.bunifuLabel5, validationObject11);
            this.bunifuLabel5.Location = new System.Drawing.Point(68, 182);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(95, 22);
            this.bunifuLabel5.TabIndex = 107;
            this.bunifuLabel5.Text = "Customer:";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnAddCustomer
            // 
            this.btnAddCustomer.AllowAnimations = true;
            this.btnAddCustomer.AllowMouseEffects = true;
            this.btnAddCustomer.AllowToggling = false;
            this.btnAddCustomer.AnimationSpeed = 200;
            this.btnAddCustomer.AutoGenerateColors = false;
            this.btnAddCustomer.AutoRoundBorders = false;
            this.btnAddCustomer.AutoSizeLeftIcon = true;
            this.btnAddCustomer.AutoSizeRightIcon = true;
            this.btnAddCustomer.BackColor = System.Drawing.Color.Transparent;
            this.btnAddCustomer.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnAddCustomer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAddCustomer.BackgroundImage")));
            this.btnAddCustomer.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddCustomer.ButtonText = "+";
            this.btnAddCustomer.ButtonTextMarginLeft = 0;
            this.btnAddCustomer.ColorContrastOnClick = 45;
            this.btnAddCustomer.ColorContrastOnHover = 45;
            this.btnAddCustomer.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnAddCustomer.CustomizableEdges = borderEdges3;
            this.btnAddCustomer.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAddCustomer.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddCustomer.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnAddCustomer.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnAddCustomer.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAddCustomer.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAddCustomer.ForeColor = System.Drawing.Color.White;
            this.btnAddCustomer.IconLeft = null;
            this.btnAddCustomer.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAddCustomer.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddCustomer.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAddCustomer.IconMarginLeft = 11;
            this.btnAddCustomer.IconPadding = 10;
            this.btnAddCustomer.IconRight = null;
            this.btnAddCustomer.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAddCustomer.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddCustomer.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAddCustomer.IconSize = 25;
            this.btnAddCustomer.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnAddCustomer.IdleBorderRadius = 0;
            this.btnAddCustomer.IdleBorderThickness = 0;
            this.btnAddCustomer.IdleFillColor = System.Drawing.Color.Empty;
            this.btnAddCustomer.IdleIconLeftImage = null;
            this.btnAddCustomer.IdleIconRightImage = null;
            this.btnAddCustomer.IndicateFocus = false;
            validationObject12.CustomErrorMessage = "";
            validationObject12.Optional = false;
            validationObject12.PropertyName = "Text";
            validationObject12.Regex = null;
            validationObject12.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.btnAddCustomer, validationObject12);
            this.btnAddCustomer.Location = new System.Drawing.Point(431, 172);
            this.btnAddCustomer.Name = "btnAddCustomer";
            this.btnAddCustomer.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddCustomer.OnDisabledState.BorderRadius = 1;
            this.btnAddCustomer.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddCustomer.OnDisabledState.BorderThickness = 1;
            this.btnAddCustomer.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddCustomer.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddCustomer.OnDisabledState.IconLeftImage = null;
            this.btnAddCustomer.OnDisabledState.IconRightImage = null;
            this.btnAddCustomer.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnAddCustomer.onHoverState.BorderRadius = 1;
            this.btnAddCustomer.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddCustomer.onHoverState.BorderThickness = 1;
            this.btnAddCustomer.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnAddCustomer.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAddCustomer.onHoverState.IconLeftImage = null;
            this.btnAddCustomer.onHoverState.IconRightImage = null;
            this.btnAddCustomer.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnAddCustomer.OnIdleState.BorderRadius = 1;
            this.btnAddCustomer.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddCustomer.OnIdleState.BorderThickness = 1;
            this.btnAddCustomer.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnAddCustomer.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAddCustomer.OnIdleState.IconLeftImage = null;
            this.btnAddCustomer.OnIdleState.IconRightImage = null;
            this.btnAddCustomer.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAddCustomer.OnPressedState.BorderRadius = 1;
            this.btnAddCustomer.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddCustomer.OnPressedState.BorderThickness = 1;
            this.btnAddCustomer.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAddCustomer.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAddCustomer.OnPressedState.IconLeftImage = null;
            this.btnAddCustomer.OnPressedState.IconRightImage = null;
            this.btnAddCustomer.Size = new System.Drawing.Size(37, 39);
            this.btnAddCustomer.TabIndex = 108;
            this.btnAddCustomer.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAddCustomer.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAddCustomer.TextMarginLeft = 0;
            this.btnAddCustomer.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAddCustomer.UseDefaultRadiusAndThickness = true;
            this.btnAddCustomer.Click += new System.EventHandler(this.btnAddCustomer_Click);
            // 
            // txtViewCustomer
            // 
            this.txtViewCustomer.AcceptsReturn = false;
            this.txtViewCustomer.AcceptsTab = false;
            this.txtViewCustomer.AnimationSpeed = 200;
            this.txtViewCustomer.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;
            this.txtViewCustomer.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.CustomSource;
            this.txtViewCustomer.AutoSizeHeight = true;
            this.txtViewCustomer.BackColor = System.Drawing.Color.Transparent;
            this.txtViewCustomer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtViewCustomer.BackgroundImage")));
            this.txtViewCustomer.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtViewCustomer.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtViewCustomer.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtViewCustomer.BorderColorIdle = System.Drawing.Color.Black;
            this.txtViewCustomer.BorderRadius = 20;
            this.txtViewCustomer.BorderThickness = 1;
            this.txtViewCustomer.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtViewCustomer.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtViewCustomer.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtViewCustomer.DefaultText = "";
            this.txtViewCustomer.FillColor = System.Drawing.Color.White;
            this.txtViewCustomer.HideSelection = true;
            this.txtViewCustomer.IconLeft = null;
            this.txtViewCustomer.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtViewCustomer.IconPadding = 10;
            this.txtViewCustomer.IconRight = null;
            this.txtViewCustomer.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtViewCustomer.Lines = new string[0];
            validationObject13.CustomErrorMessage = "";
            validationObject13.Optional = false;
            validationObject13.PropertyName = "Text";
            validationObject13.Regex = null;
            validationObject13.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.txtViewCustomer, validationObject13);
            this.txtViewCustomer.Location = new System.Drawing.Point(169, 172);
            this.txtViewCustomer.MaxLength = 32767;
            this.txtViewCustomer.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtViewCustomer.Modified = false;
            this.txtViewCustomer.Multiline = false;
            this.txtViewCustomer.Name = "txtViewCustomer";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtViewCustomer.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtViewCustomer.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtViewCustomer.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Black;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtViewCustomer.OnIdleState = stateProperties12;
            this.txtViewCustomer.Padding = new System.Windows.Forms.Padding(3);
            this.txtViewCustomer.PasswordChar = '\0';
            this.txtViewCustomer.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtViewCustomer.PlaceholderText = "Search customer...";
            this.txtViewCustomer.ReadOnly = false;
            this.txtViewCustomer.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtViewCustomer.SelectedText = "";
            this.txtViewCustomer.SelectionLength = 0;
            this.txtViewCustomer.SelectionStart = 0;
            this.txtViewCustomer.ShortcutsEnabled = true;
            this.txtViewCustomer.Size = new System.Drawing.Size(256, 39);
            this.txtViewCustomer.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtViewCustomer.TabIndex = 0;
            this.txtViewCustomer.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtViewCustomer.TextMarginBottom = 0;
            this.txtViewCustomer.TextMarginLeft = 3;
            this.txtViewCustomer.TextMarginTop = 1;
            this.txtViewCustomer.TextPlaceholder = "Search customer...";
            this.txtViewCustomer.UseSystemPasswordChar = false;
            this.txtViewCustomer.WordWrap = true;
            this.txtViewCustomer.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtViewCustomer_KeyDown);
            // 
            // txtPWDOSCA
            // 
            this.txtPWDOSCA.AcceptsReturn = false;
            this.txtPWDOSCA.AcceptsTab = false;
            this.txtPWDOSCA.AnimationSpeed = 200;
            this.txtPWDOSCA.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;
            this.txtPWDOSCA.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.CustomSource;
            this.txtPWDOSCA.AutoSizeHeight = true;
            this.txtPWDOSCA.BackColor = System.Drawing.Color.Transparent;
            this.txtPWDOSCA.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPWDOSCA.BackgroundImage")));
            this.txtPWDOSCA.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPWDOSCA.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPWDOSCA.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPWDOSCA.BorderColorIdle = System.Drawing.Color.Black;
            this.txtPWDOSCA.BorderRadius = 20;
            this.txtPWDOSCA.BorderThickness = 1;
            this.txtPWDOSCA.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPWDOSCA.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPWDOSCA.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtPWDOSCA.DefaultText = "";
            this.txtPWDOSCA.FillColor = System.Drawing.Color.White;
            this.txtPWDOSCA.HideSelection = true;
            this.txtPWDOSCA.IconLeft = null;
            this.txtPWDOSCA.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPWDOSCA.IconPadding = 10;
            this.txtPWDOSCA.IconRight = null;
            this.txtPWDOSCA.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPWDOSCA.Lines = new string[0];
            validationObject14.CustomErrorMessage = "";
            validationObject14.Optional = true;
            validationObject14.PropertyName = "Text";
            validationObject14.Regex = "^\\d+$";
            validationObject14.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.Integer;
            this.validationProvider1.SetLink(this.txtPWDOSCA, validationObject14);
            this.txtPWDOSCA.Location = new System.Drawing.Point(169, 230);
            this.txtPWDOSCA.MaxLength = 5;
            this.txtPWDOSCA.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPWDOSCA.Modified = false;
            this.txtPWDOSCA.Multiline = false;
            this.txtPWDOSCA.Name = "txtPWDOSCA";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPWDOSCA.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPWDOSCA.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPWDOSCA.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Black;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPWDOSCA.OnIdleState = stateProperties16;
            this.txtPWDOSCA.Padding = new System.Windows.Forms.Padding(3);
            this.txtPWDOSCA.PasswordChar = '\0';
            this.txtPWDOSCA.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPWDOSCA.PlaceholderText = "";
            this.txtPWDOSCA.ReadOnly = false;
            this.txtPWDOSCA.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPWDOSCA.SelectedText = "";
            this.txtPWDOSCA.SelectionLength = 0;
            this.txtPWDOSCA.SelectionStart = 0;
            this.txtPWDOSCA.ShortcutsEnabled = true;
            this.txtPWDOSCA.Size = new System.Drawing.Size(256, 39);
            this.txtPWDOSCA.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPWDOSCA.TabIndex = 111;
            this.txtPWDOSCA.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPWDOSCA.TextMarginBottom = 0;
            this.txtPWDOSCA.TextMarginLeft = 3;
            this.txtPWDOSCA.TextMarginTop = 1;
            this.txtPWDOSCA.TextPlaceholder = "";
            this.txtPWDOSCA.UseSystemPasswordChar = false;
            this.txtPWDOSCA.Visible = false;
            this.txtPWDOSCA.WordWrap = true;
            this.txtPWDOSCA.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txtPWDOSCA_KeyPress);
            // 
            // txtORNumber
            // 
            this.txtORNumber.AcceptsReturn = false;
            this.txtORNumber.AcceptsTab = false;
            this.txtORNumber.AnimationSpeed = 200;
            this.txtORNumber.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtORNumber.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtORNumber.AutoSizeHeight = true;
            this.txtORNumber.BackColor = System.Drawing.Color.Transparent;
            this.txtORNumber.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtORNumber.BackgroundImage")));
            this.txtORNumber.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtORNumber.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtORNumber.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtORNumber.BorderColorIdle = System.Drawing.Color.White;
            this.txtORNumber.BorderRadius = 1;
            this.txtORNumber.BorderThickness = 1;
            this.txtORNumber.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtORNumber.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtORNumber.DefaultFont = new System.Drawing.Font("Arial", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtORNumber.DefaultText = "";
            this.txtORNumber.Enabled = false;
            this.txtORNumber.FillColor = System.Drawing.Color.White;
            this.txtORNumber.HideSelection = true;
            this.txtORNumber.IconLeft = null;
            this.txtORNumber.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtORNumber.IconPadding = 10;
            this.txtORNumber.IconRight = null;
            this.txtORNumber.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtORNumber.Lines = new string[0];
            validationObject15.CustomErrorMessage = "";
            validationObject15.Optional = false;
            validationObject15.PropertyName = "Text";
            validationObject15.Regex = "^\\d+$";
            validationObject15.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.Integer;
            this.validationProvider1.SetLink(this.txtORNumber, validationObject15);
            this.txtORNumber.Location = new System.Drawing.Point(188, 343);
            this.txtORNumber.MaxLength = 4;
            this.txtORNumber.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtORNumber.Modified = false;
            this.txtORNumber.Multiline = false;
            this.txtORNumber.Name = "txtORNumber";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtORNumber.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtORNumber.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtORNumber.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.White;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtORNumber.OnIdleState = stateProperties20;
            this.txtORNumber.Padding = new System.Windows.Forms.Padding(3);
            this.txtORNumber.PasswordChar = '\0';
            this.txtORNumber.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtORNumber.PlaceholderText = "";
            this.txtORNumber.ReadOnly = false;
            this.txtORNumber.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtORNumber.SelectedText = "";
            this.txtORNumber.SelectionLength = 0;
            this.txtORNumber.SelectionStart = 0;
            this.txtORNumber.ShortcutsEnabled = true;
            this.txtORNumber.Size = new System.Drawing.Size(176, 37);
            this.txtORNumber.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtORNumber.TabIndex = 1;
            this.txtORNumber.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtORNumber.TextMarginBottom = 0;
            this.txtORNumber.TextMarginLeft = 3;
            this.txtORNumber.TextMarginTop = 1;
            this.txtORNumber.TextPlaceholder = "";
            this.txtORNumber.UseSystemPasswordChar = false;
            this.txtORNumber.WordWrap = true;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14.25F);
            this.bunifuLabel6.ForeColor = System.Drawing.Color.Black;
            validationObject16.CustomErrorMessage = "";
            validationObject16.Optional = false;
            validationObject16.PropertyName = "Text";
            validationObject16.Regex = null;
            validationObject16.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.bunifuLabel6, validationObject16);
            this.bunifuLabel6.Location = new System.Drawing.Point(132, 355);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(50, 22);
            this.bunifuLabel6.TabIndex = 113;
            this.bunifuLabel6.Text = "OR #:";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblPWDORSC
            // 
            this.lblPWDORSC.AllowParentOverrides = false;
            this.lblPWDORSC.AutoEllipsis = false;
            this.lblPWDORSC.CursorType = null;
            this.lblPWDORSC.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14.25F);
            this.lblPWDORSC.ForeColor = System.Drawing.Color.Black;
            validationObject17.CustomErrorMessage = "";
            validationObject17.Optional = false;
            validationObject17.PropertyName = "Text";
            validationObject17.Regex = null;
            validationObject17.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.lblPWDORSC, validationObject17);
            this.lblPWDORSC.Location = new System.Drawing.Point(103, 240);
            this.lblPWDORSC.Name = "lblPWDORSC";
            this.lblPWDORSC.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblPWDORSC.Size = new System.Drawing.Size(16, 22);
            this.lblPWDORSC.TabIndex = 114;
            this.lblPWDORSC.Text = "#:";
            this.lblPWDORSC.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblPWDORSC.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.lblPWDORSC.Visible = false;
            // 
            // lblTransCount
            // 
            this.lblTransCount.AllowParentOverrides = false;
            this.lblTransCount.AutoEllipsis = false;
            this.lblTransCount.CursorType = null;
            this.lblTransCount.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14.25F);
            this.lblTransCount.ForeColor = System.Drawing.Color.Black;
            validationObject18.CustomErrorMessage = "";
            validationObject18.Optional = false;
            validationObject18.PropertyName = "Text";
            validationObject18.Regex = null;
            validationObject18.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.lblTransCount, validationObject18);
            this.lblTransCount.Location = new System.Drawing.Point(486, 67);
            this.lblTransCount.Name = "lblTransCount";
            this.lblTransCount.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblTransCount.Size = new System.Drawing.Size(16, 22);
            this.lblTransCount.TabIndex = 115;
            this.lblTransCount.Text = "#:";
            this.lblTransCount.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblTransCount.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.lblTransCount.Visible = false;
            // 
            // lblTranstotal
            // 
            this.lblTranstotal.AllowParentOverrides = false;
            this.lblTranstotal.AutoEllipsis = false;
            this.lblTranstotal.CursorType = null;
            this.lblTranstotal.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14.25F);
            this.lblTranstotal.ForeColor = System.Drawing.Color.Black;
            validationObject19.CustomErrorMessage = "";
            validationObject19.Optional = false;
            validationObject19.PropertyName = "Text";
            validationObject19.Regex = null;
            validationObject19.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.lblTranstotal, validationObject19);
            this.lblTranstotal.Location = new System.Drawing.Point(508, 67);
            this.lblTranstotal.Name = "lblTranstotal";
            this.lblTranstotal.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblTranstotal.Size = new System.Drawing.Size(16, 22);
            this.lblTranstotal.TabIndex = 116;
            this.lblTranstotal.Text = "#:";
            this.lblTranstotal.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblTranstotal.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.lblTranstotal.Visible = false;
            // 
            // validationProvider1
            // 
            this.validationProvider1.ErrorColor = System.Drawing.Color.Crimson;
            // 
            // btnGenerateOR
            // 
            this.btnGenerateOR.AllowAnimations = true;
            this.btnGenerateOR.AllowMouseEffects = true;
            this.btnGenerateOR.AllowToggling = false;
            this.btnGenerateOR.AnimationSpeed = 200;
            this.btnGenerateOR.AutoGenerateColors = false;
            this.btnGenerateOR.AutoRoundBorders = false;
            this.btnGenerateOR.AutoSizeLeftIcon = true;
            this.btnGenerateOR.AutoSizeRightIcon = true;
            this.btnGenerateOR.BackColor = System.Drawing.Color.Transparent;
            this.btnGenerateOR.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnGenerateOR.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnGenerateOR.BackgroundImage")));
            this.btnGenerateOR.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGenerateOR.ButtonText = "Generate OR";
            this.btnGenerateOR.ButtonTextMarginLeft = 0;
            this.btnGenerateOR.ColorContrastOnClick = 45;
            this.btnGenerateOR.ColorContrastOnHover = 45;
            this.btnGenerateOR.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnGenerateOR.CustomizableEdges = borderEdges4;
            this.btnGenerateOR.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnGenerateOR.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGenerateOR.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnGenerateOR.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnGenerateOR.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnGenerateOR.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnGenerateOR.ForeColor = System.Drawing.Color.White;
            this.btnGenerateOR.IconLeft = null;
            this.btnGenerateOR.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGenerateOR.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnGenerateOR.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnGenerateOR.IconMarginLeft = 11;
            this.btnGenerateOR.IconPadding = 10;
            this.btnGenerateOR.IconRight = null;
            this.btnGenerateOR.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGenerateOR.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnGenerateOR.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnGenerateOR.IconSize = 25;
            this.btnGenerateOR.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnGenerateOR.IdleBorderRadius = 0;
            this.btnGenerateOR.IdleBorderThickness = 0;
            this.btnGenerateOR.IdleFillColor = System.Drawing.Color.Empty;
            this.btnGenerateOR.IdleIconLeftImage = null;
            this.btnGenerateOR.IdleIconRightImage = null;
            this.btnGenerateOR.IndicateFocus = false;
            validationObject20.CustomErrorMessage = "";
            validationObject20.Optional = false;
            validationObject20.PropertyName = "Text";
            validationObject20.Regex = null;
            validationObject20.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.btnGenerateOR, validationObject20);
            this.btnGenerateOR.Location = new System.Drawing.Point(371, 343);
            this.btnGenerateOR.Name = "btnGenerateOR";
            this.btnGenerateOR.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGenerateOR.OnDisabledState.BorderRadius = 1;
            this.btnGenerateOR.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGenerateOR.OnDisabledState.BorderThickness = 1;
            this.btnGenerateOR.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGenerateOR.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGenerateOR.OnDisabledState.IconLeftImage = null;
            this.btnGenerateOR.OnDisabledState.IconRightImage = null;
            this.btnGenerateOR.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnGenerateOR.onHoverState.BorderRadius = 1;
            this.btnGenerateOR.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGenerateOR.onHoverState.BorderThickness = 1;
            this.btnGenerateOR.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnGenerateOR.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnGenerateOR.onHoverState.IconLeftImage = null;
            this.btnGenerateOR.onHoverState.IconRightImage = null;
            this.btnGenerateOR.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnGenerateOR.OnIdleState.BorderRadius = 1;
            this.btnGenerateOR.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGenerateOR.OnIdleState.BorderThickness = 1;
            this.btnGenerateOR.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnGenerateOR.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnGenerateOR.OnIdleState.IconLeftImage = null;
            this.btnGenerateOR.OnIdleState.IconRightImage = null;
            this.btnGenerateOR.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnGenerateOR.OnPressedState.BorderRadius = 1;
            this.btnGenerateOR.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGenerateOR.OnPressedState.BorderThickness = 1;
            this.btnGenerateOR.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnGenerateOR.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnGenerateOR.OnPressedState.IconLeftImage = null;
            this.btnGenerateOR.OnPressedState.IconRightImage = null;
            this.btnGenerateOR.Size = new System.Drawing.Size(95, 37);
            this.btnGenerateOR.TabIndex = 117;
            this.btnGenerateOR.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnGenerateOR.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnGenerateOR.TextMarginLeft = 0;
            this.btnGenerateOR.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnGenerateOR.UseDefaultRadiusAndThickness = true;
            this.btnGenerateOR.Click += new System.EventHandler(this.btnGenerateOR_Click);
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Arial Rounded MT Bold", 12F);
            this.bunifuLabel7.ForeColor = System.Drawing.Color.Black;
            validationObject21.CustomErrorMessage = "";
            validationObject21.Optional = false;
            validationObject21.PropertyName = "Text";
            validationObject21.Regex = null;
            validationObject21.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.bunifuLabel7, validationObject21);
            this.bunifuLabel7.Location = new System.Drawing.Point(100, 384);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(82, 36);
            this.bunifuLabel7.TabIndex = 118;
            this.bunifuLabel7.Text = "Amount \r\nTendered:";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopRight;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Black;
            this.bunifuPanel2.BorderRadius = 3;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel2.Controls.Add(this.txtAmount);
            validationObject22.CustomErrorMessage = "";
            validationObject22.Optional = false;
            validationObject22.PropertyName = "Text";
            validationObject22.Regex = null;
            validationObject22.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.bunifuPanel2, validationObject22);
            this.bunifuPanel2.Location = new System.Drawing.Point(68, 285);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(400, 52);
            this.bunifuPanel2.TabIndex = 119;
            // 
            // frmReturnPayment
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(583, 514);
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.btnGenerateOR);
            this.Controls.Add(this.lblTranstotal);
            this.Controls.Add(this.lblTransCount);
            this.Controls.Add(this.lblPWDORSC);
            this.Controls.Add(this.txtORNumber);
            this.Controls.Add(this.txtCash);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.txtPWDOSCA);
            this.Controls.Add(this.txtViewCustomer);
            this.Controls.Add(this.btnAddCustomer);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.btnConfirm);
            this.Controls.Add(this.btnCancel);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmReturnPayment";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Payment";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmPayment_FormClosing);
            this.Load += new System.EventHandler(this.frmPayment_Load);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.bunifuPanel2.ResumeLayout(false);
            this.bunifuPanel2.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox txtCash;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCancel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnConfirm;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private System.Windows.Forms.Button btnExit;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        public Bunifu.UI.WinForms.BunifuTextBox txtAmount;
        private Bunifu.Framework.UI.BunifuTileButton btnClose;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAddCustomer;
        private Bunifu.UI.WinForms.BunifuTextBox txtViewCustomer;
        private Bunifu.UI.WinForms.BunifuTextBox txtPWDOSCA;
        private Bunifu.UI.WinForms.BunifuTextBox txtORNumber;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel lblPWDORSC;
        private Bunifu.UI.WinForms.BunifuLabel lblTransCount;
        private Bunifu.UI.WinForms.BunifuLabel lblTranstotal;
        private Kimtoo.ValidationProvider.ValidationProvider validationProvider1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnGenerateOR;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
    }
}